chaijs/loupe

- .travis.yml
- package.json
Hello there!
I was taking a look at #9 and I found that build was failing there because loupe tells travis to build over node 0.8 which is not supported from `jsmd` anymore. (IMHO, it should not be supported from anyone 😸).
So this PR adds all supported node versions to `.travis.yml`, totally stolen from [chai's](https://github.com/chaijs/chai/blob/9e16c8f1ee42b38688ce3a882ae812d3195b8984/.travis.yml)
Thank you all!
> Add supported node versions to .travis.yml

- .github/workflows/build.yml
Semantic release is broken because it uses `event` not `event_name`, and also uses the old `semantic-release pre`/`post` steps.
> fix semantic release

- package.json
This uses the `files` array to avoid publishing all the test files, bench files, rollup config, karma config, Makefile, etc.
> fix: dont emit test files for published package

- lib/symbol.js
- test/symbols.js
inspect(Symbol()) was returning incorrect value, due to:
```js
Symbol().description;        // undefined
```
> Fix empty Symbol incorrect return

- index.js
- test/acceptance.js
Mentioned in https://github.com/chaijs/loupe/issues/37#issuecomment-769746796 is that Loupe ignores `customInspect` symbols for "plain" objects. This fixes that.
Fixes https://github.com/chaijs/loupe/issues/37
> fix: ensure custominspect works for plain objects

- lib/function.js
- package-lock.json
- package.json
- test/acceptance.js
Mistakenly, we added the `get-function-name` package when it should be `get-func-name`. 
This fixes that, and adds a test that breaks with `get-function-name`.
Fixes #42
> fix(function): use correct `get-func-name` package

- lib/helpers.js
- test/objects.js
> fix: ensure complex object keys are quoted

- index.js
- lib/promise.js
- package-lock.json
- package.json
- test/acceptance.js
- test/promises.js
Loupe fails on Node since 16 which dropped `process.binding('util').getPromiseDetail`. See https://github.com/nodejs/node/issues/40054 for more.
This more gracefully degrades when that function is not available.
> Degrade more gracefully on promise inpsection capabilities

- index.js
- package.json
node "util" is now mapped to an empty object and checked in runtime.
addresses https://github.com/chaijs/chai/issues/1447
> fix: ensure no warnings when bundled

- package.json
when #54 was merged to fix #53, it also regressed the fix in #50 back into showing bundle warnings.
this PR ensures the es5 loupe.js is picked for browsers, while still mapping util to an empty object (for the `require("util")` call).
also did a tiny adjustment (string -> number) to the `eslintConfig` to match its schema.
> fix: ensure es5 target is bundle-compatible

- index.js
- test/objects.js
Fixes this: https://github.com/chaijs/loupe/issues/56
> fix: inspect null prototype objects

- lib/date.js
- test/dates.js
This PR will make sure that `loupe` will return `"Invalid Date"` if a `Date` object is invalid. It does **not** deal with _how_ the `Date` object became invalid as that depends on JS engine.
See https://github.com/chaijs/loupe/issues/58#issuecomment-1303259185 for a comparison between V8 and Firefox's SpiderMoney.
> fix: Invalid Date object will throw a TypeError (#58)

- package.json
`get-func-name` is vulnerable up to (but excluding) `2.0.0` -- change the requirement to `^2.0.1` to shut dependabot up
> upgrade get-func-name for CVE-2023-43646

- .github/workflows/build.yml
- .github/workflows/publish.yml
Node 16 is now EOL so we should only support 18+
This also changes the publish step to be like deep-eql.
> use standardised publish step

- src/function.ts
- src/index.ts
- test/functions.js
`loupe` currently doesn't differentiate between the different functions and it probably should.
See https://github.com/chaijs/chai/pull/1566
> Add support for different types of functions

- src/helpers.ts
- test/strings.js
> Support inspect on strings with unicode

- package-lock.json
- package.json
It looks like since https://github.com/chaijs/loupe/pull/62, `get-func-name` is no longer used, so we can remove it from the dependencies.
NOTE: this doesn't affect `chai` for now since it's using loupe v2.
> chore: remove unused get-func-name dependency

- src/error.ts
- src/object.ts
- test/errors.js
Fixes chaijs/chai#1645
We already handle circular references in objects, but do not do the same for `Error` objects. This change adds the same `seen` logic to error inspection as we have in object inspection.
Also adds `cause` to the list of "built in" properties
> fix: handle circular refs in errors

- tsconfig.json
Some dependencies ship types which fail with our strictness level. This should skip them so our builds continue to work.
> chore: enable `skipLibCheck`

- package-lock.json
- package.json
i think this will sort what you're trying to do @keithamus
> chore: install playwright deps before playwright

- src/html.ts
- src/index.ts
- test/html.js
An `HTMLCollection` assumes all items are `Element`s, a `NodeList` however may also include `Node`s such as `Text` and `Comment`, which does not include the `getAttributeNames` method.
Stops the error described here https://github.com/chaijs/chai/issues/1680 but logging that div from inside the iframe changes the output a bit, logging it as a regular object ( `HTMLDivElement{ …(1) }` ), but in a way that is still acceptable to me for now, until we wait for the proper fix described here: https://github.com/chaijs/chai/issues/1680#issuecomment-2717939982
> fix: do not treat a NodeList as HTMLCollection

- src/promise.ts
- test/promises.js
Dumbs it down to always return `Promise{...}` regardless of the state
and platform/engine we're in, since Node has deprecated the private API
we were using.
Fixes #108
> feat: simplify promise inspection

- src/index.ts
- test/acceptance.js
Fixes #74
Removes support for `inspect` properties on objects acting as custom
inspect functions.
After this change, you _must_ use `Symbol('nodejs.util.inspect.custom')`
or `Symbol('chai/inspect')`.
> feat: drop support for non-symbol inspect properties
